services:
  postgres:
    container_name: postgres
    image: postgis/postgis
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: always
    volumes:
      - waterwatch_data:/var/lib/postgresql/data
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 120s
      retries: 5
      start_period: 30s
      timeout: 10s
    command:
      - postgres
      - -c
      - max_connections=${POSTGRES_MAX_CONNECTIONS}
      - -c
      - idle_in_transaction_session_timeout=${POSTGRES_IDLE_IN_TRANSACTION_SESSION_TIMEOUT}
      - -c
      - statement_timeout=${POSTGRES_STATEMENT_TIMEOUT}

  django_backend_app:
    container_name: django_backend_app
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ../
      dockerfile: production/dockerfile.backend.prod
    image: django_backend_app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - gunicorn_socket:/run
      - static_files:/app/static
      - media_files:/app/media
    networks:
      - web
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/api/health/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend:
    container_name: nginx_frontend
    depends_on:
      django_backend_app:
        condition: service_started
    build:
      context: ../
      dockerfile: production/dockerfile.frontend.prod
    image: nginx_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.nginx:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ../assets/countries.sql:/usr/share/nginx/html/countries.sql:ro
      - gunicorn_socket:/run
      - static_files:/backend_app/static
      - media_files:/backend_app/media
    networks:
      - web
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1m30s
      retries: 3
      timeout: 10s
      start_period: 30s
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  waterwatch_data:
    name: waterwatch_data
    driver: local
  gunicorn_socket:
  static_files:
  media_files:

networks:
  web:
    driver: bridge
